@startuml

title __LAB11P2's Class Diagram__\n

  namespace  {
    namespace ab11p2 {
      class Lab11p2.Main {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace ab11p2 {
      class Lab11p2.Message {
          ~ messageContent : String
          + Message()
          + getMessageContent()
      }
    }
  }
  

  namespace  {
    namespace ab11p2 {
      class Lab11p2.MessagePublisher {
          - observers : List<Observer>
          + attach()
          + detach()
          + notifyUpdate()
      }
    }
  }
  

  namespace  {
    namespace ab11p2 {
      class Lab11p2.MessageSubscriberOne {
          + update()
      }
    }
  }
  

  namespace  {
    namespace ab11p2 {
      class Lab11p2.MessageSubscriberThree {
          + update()
      }
    }
  }
  

  namespace  {
    namespace ab11p2 {
      class Lab11p2.MessageSubscriberTwo {
          + update()
      }
    }
  }
  

  namespace  {
    namespace ab11p2 {
      interface Lab11p2.Observer {
          {abstract} + update()
      }
    }
  }
  

  namespace  {
    namespace ab11p2 {
      interface Lab11p2.Subject {
          {abstract} + attach()
          {abstract} + detach()
          {abstract} + notifyUpdate()
      }
    }
  }
  

  Lab11p2.MessagePublisher .up.|> Lab11p2.Subject
  Lab11p2.MessageSubscriberOne .up.|> Lab11p2.Observer
  Lab11p2.MessageSubscriberThree .up.|> Lab11p2.Observer
  Lab11p2.MessageSubscriberTwo .up.|> Lab11p2.Observer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
